#include "init.h"

u64 U[NUMBER_SCALAR_REGISTER];
i64 S[NUMBER_SCALAR_REGISTER];
f64 F[NUMBER_SCALAR_REGISTER];

u64 V[NUMBER_VECTOR_REGISTER][8];
i64 T[NUMBER_VECTOR_REGISTER][8];
f64 G[NUMBER_VECTOR_REGISTER][8];

uint8_t CF = 0;
u64 IP = 0;
